### ISSUE TITLE
Reablocks does not work on NextJs project @(14.2.5)

### ISSUE THREAD

**Issue by B3Kay** [reaviz/reablocks#250]
## I'm submitting a Bug Report

<pre><code>
[ ] Regression
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current behavior
Initiated NextJS project with tailwind, installing Reablocks,
adds theme provider and app does not work. Gives error in terminal.

## Expected behavior
Should just work.

## Minimal reproduction of the problem with instructions

* Step 1
Init  next js project. (14.2.5)
```

npx create-next-app@latest

What is your project named? test-nextjs-reablocks
Would you like to use TypeScript? -  Yes
Would you like to use ESLint? -  Yes
Would you like to use Tailwind CSS? -  Yes
Would you like to use `src/` directory?  - Yes
Would you like to use App Router? (recommended) -  Yes
Would you like to customize the default import alias (@/*)? No 
```

* Step 2
Install reablocks

cd test-nextjs-reablocks
npx reablocks-cli@latest init

* Step 3
Add ThemeProvider to root layout

`import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider, theme } from 'reablocks';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
`

## Environment

<pre><code>
Libs:
"next": "14.2.5",
"reablocks": "^7.6.16",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",

Browser:
- [X] Chrome (desktop) version Version 126.0.6478.183 (Officiell version) (64 bitar)
 
For Tooling issues:
- Node version: v20.10.0
- Platform:  WSL subsystem Ubuntu  20 on Windows

## Log
➜  nextjs-reablocks git:(main) ✗ npm run dev

> nextjs-reablocks@0.1.0 dev
> next dev --turbo

  ▲ Next.js 14.2.5 (turbo)
  - Local:        http://localhost:3000

 ✓ Starting...
 ✓ Ready in 899ms
 ○ Compiling / ...
 ✓ Compiled / in 7.3s
 GET / 200 in 7527ms
 ✓ Compiled /favicon.ico in 196ms
 GET /favicon.ico 200 in 255ms
 ✓ Compiled in 1324ms
 ✓ Compiled / in 135ms
TypeError: (0 , __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$future$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__.createContext) is not a function
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:14:262
    at [project]/node_modules/framer-motion/dist/es/context/MotionConfigContext.mjs [app-rsc] (ecmascript) (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:21:3)
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:501:185
    at [project]/node_modules/framer-motion/dist/es/motion/index.mjs [app-rsc] (ecmascript) (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:586:3)
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:11210:170
    at [project]/node_modules/framer-motion/dist/es/render/dom/motion.mjs [app-rsc] (ecmascript) (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:11260:3)
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_reablocks_dist_index_e4e72f.js:277:178
    at [project]/node_modules/reablocks/dist/index.js [app-rsc] (ecmascript) (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_reablocks_dist_index_e4e72f.js:10400:3)
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:41:146
    at [project]/src/app/layout.tsx [app-rsc] (ecmascript) (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:76:3)
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at Module.default (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:80:20)
    at tree.layout (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_next_1ae572._.js:5929:169)
    at e7 (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:396757)
    at /home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:7437
    at /home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/server/lib/trace/tracer.js:140:36
    at NoopContextManager.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/server/lib/trace/tracer.js:122:103
    at NoopContextManager.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NextTracerImpl.trace (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/server/lib/trace/tracer.js:122:28)
    at rU (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:7314)
    at /home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:6151
    at /home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/server/lib/trace/tracer.js:140:36
    at NoopContextManager.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/server/lib/trace/tracer.js:122:103
    at NoopContextManager.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NextTracerImpl.trace (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/server/lib/trace/tracer.js:122:28)
    at rL (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:6082) {
  digest: '2137806203'
}
 ⨯ TypeError: (0 , __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$future$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__.createContext) is not a function
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:14:262
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:501:185
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:11210:170
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_reablocks_dist_index_e4e72f.js:277:178
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:41:146
    at [project]/src/app/layout.tsx [app-rsc] (ecmascript) (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:76:3)
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at Module.default (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:80:20)
    at tree.layout (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_next_1ae572._.js:5929:169)
digest: "2137806203"
 ⨯ TypeError: (0 , __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$future$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__.createContext) is not a function
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:14:262
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:501:185
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:11210:170
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_reablocks_dist_index_e4e72f.js:277:178
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:41:146
    at [project]/src/app/layout.tsx [app-rsc] (ecmascript) (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:76:3)
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at Module.default (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:80:20)
    at tree.layout (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_next_1ae572._.js:5929:169)
digest: "2137806203"
 ⨯ TypeError: (0 , __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$future$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__.createContext) is not a function
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:14:262
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:501:185
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:11210:170
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_reablocks_dist_index_e4e72f.js:277:178
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:41:146
    at [project]/src/app/layout.tsx [app-rsc] (ecmascript) (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:76:3)
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at Module.default (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:80:20)
    at tree.layout (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_next_1ae572._.js:5929:169)
digest: "2137806203"
 ⨯ TypeError: (0 , __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$future$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__.createContext) is not a function
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:14:262
    at [project]/node_modules/framer-motion/dist/es/context/MotionConfigContext.mjs [app-rsc] (ecmascript) (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:21:3)
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:501:185
    at [project]/node_modules/framer-motion/dist/es/motion/index.mjs [app-rsc] (ecmascript) (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:586:3)
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:11210:170
    at [project]/node_modules/framer-motion/dist/es/render/dom/motion.mjs [app-rsc] (ecmascript) (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_framer-motion_dist_es_62ea84._.js:11260:3)
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_reablocks_dist_index_e4e72f.js:277:178
    at [project]/node_modules/reablocks/dist/index.js [app-rsc] (ecmascript) (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_reablocks_dist_index_e4e72f.js:10400:3)
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at /home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:41:146
    at [project]/src/app/layout.tsx [app-rsc] (ecmascript) (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:76:3)
    at instantiateModule (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:520:23)
    at getOrInstantiateModuleFromParent (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:572:12)
    at esmImport (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[turbopack]_runtime.js:122:20)
    at Module.default (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/[root of the server]__dd06ad._.js:80:20)
    at tree.layout (/home/b3kay/code/testing/nextjs-reablocks/.next/server/chunks/ssr/node_modules_next_1ae572._.js:5929:169)
    at e7 (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:396757)
    at /home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:7437
    at /home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/server/lib/trace/tracer.js:140:36
    at NoopContextManager.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/server/lib/trace/tracer.js:122:103
    at NoopContextManager.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NextTracerImpl.trace (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/server/lib/trace/tracer.js:122:28)
    at rU (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:7314)
    at /home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:6151
    at /home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/server/lib/trace/tracer.js:140:36
    at NoopContextManager.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/server/lib/trace/tracer.js:122:103
    at NoopContextManager.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NextTracerImpl.trace (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/server/lib/trace/tracer.js:122:28)
    at rL (/home/b3kay/code/testing/nextjs-reablocks/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:39:6082) {
  digest: '2137806203',
  page: '/'
}
 ✓ Compiled in 275ms
 ○ Compiling /_error ...
 ✓ Compiled /_error in 1036ms
 GET / 500 in 1888ms
 GET /favicon.ico 200 in 81ms
 ✓ Compiled in 45ms
 ✓ Compiled / in 111ms

**Comment by amcdnl** [comment]
Any chance you could provide a sample repo?

**Comment by amcdnl** [comment]
We actually use reablocks on reablocks.dev which is a NextJS site so I'd want to see what might be different.

**Comment by Siddartha03** [comment]
> We actually use reablocks on reablocks.dev which is a NextJS site so I'd want to see what might be different.

In Next.js new version 14.2.5, reablocks is not working. I'm also getting same issue what @B3Kay  got.

**Comment by B3Kay** [comment]
I've solved it now, but this could be added to the documentation of Reablocks like: https://nextui.org/docs/frameworks/nextjs#setup-provider

## Problem
The problem is that you cannot use useContext on a server component. 

https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#using-context-providers


## Solution:
This can easily be solved.  By making client component and wrap the themeProvider.

```
'use client'
 
import { createContext } from 'react'
 
export const ThemeContext = createContext({})
 
export default function ThemeProvider({
  children,
}: {
  children: React.ReactNode
}) {
  return <ThemeContext.Provider value="dark">{children}</ThemeContext.Provider>
}
```
And then in the layout wrap the children with the themeprovider.

```
import ThemeProvider from './theme-provider'
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  )
}
```

Library creators can also mark their packages that they will be used by the client. 
https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#advice-for-library-authors
